// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides AI-powered suggestions for journal entry topics or prompts based on class activities and student performance.
 *
 * - generateEntrySuggestions - A function that generates journal entry suggestions.
 * - GenerateEntrySuggestionsInput - The input type for the generateEntrySuggestions function.
 * - GenerateEntrySuggestionsOutput - The return type for the generateEntrySuggestions function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateEntrySuggestionsInputSchema = z.object({
  classSubject: z.string().describe('The class or subject for which to generate journal entry suggestions.'),
  recentActivities: z.string().describe('A summary of recent class activities.'),
  studentPerformanceData: z.string().describe('A summary of student performance data, including any areas of concern.'),
});
export type GenerateEntrySuggestionsInput = z.infer<typeof GenerateEntrySuggestionsInputSchema>;

const GenerateEntrySuggestionsOutputSchema = z.object({
  suggestions: z.array(
    z.string().describe('A list of suggested journal entry topics or prompts.')
  ).describe('A list of suggested journal entry topics or prompts based on the input data.'),
});
export type GenerateEntrySuggestionsOutput = z.infer<typeof GenerateEntrySuggestionsOutputSchema>;

export async function generateEntrySuggestions(input: GenerateEntrySuggestionsInput): Promise<GenerateEntrySuggestionsOutput> {
  return generateEntrySuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEntrySuggestionsPrompt',
  input: {
    schema: z.object({
      classSubject: z.string().describe('The class or subject for which to generate journal entry suggestions.'),
      recentActivities: z.string().describe('A summary of recent class activities.'),
      studentPerformanceData: z.string().describe('A summary of student performance data, including any areas of concern.'),
    }),
  },
  output: {
    schema: z.object({
      suggestions: z.array(
        z.string().describe('A list of suggested journal entry topics or prompts.')
      ).describe('A list of suggested journal entry topics or prompts based on the input data.'),
    }),
  },
  prompt: `You are an AI assistant designed to help teachers generate journal entry topics or prompts for their classes.

  Based on the recent class activities and student performance data provided, suggest relevant and engaging journal entry topics or prompts for the teacher to use in their journal.

  Class/Subject: {{{classSubject}}}
  Recent Activities: {{{recentActivities}}}
  Student Performance Data: {{{studentPerformanceData}}}

  Suggestions:`,
});

const generateEntrySuggestionsFlow = ai.defineFlow<
  typeof GenerateEntrySuggestionsInputSchema,
  typeof GenerateEntrySuggestionsOutputSchema
>({
  name: 'generateEntrySuggestionsFlow',
  inputSchema: GenerateEntrySuggestionsInputSchema,
  outputSchema: GenerateEntrySuggestionsOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
